### ISSUE TITLE
searching by the amount of words in repo name

### ISSUE THREAD

**Issue by trinib** [gennaro-tedesco/gh-s#19]
is it normal to find like less than 20% of repositories with a popular word like "awesome"..   alot of repos do not get find

**Comment by trinib** [comment]
I do not know if it would be better for the searching algorithm to have a function to search for the amount of words in the repo name ..  like 'user/awesome' = one word and 'user/awesome-python = two, eliminateing all search for one name repos. for maybe you can find more repos this way?

**Comment by gennaro-tedesco** [comment]
Good afternoon! Could you provide an example of repositories that are not found? The search is returned usually by total number of stars (and you can filter and scroll the list down): in general _all_ results of the GitHub call are returned after pagination (so if you have a specific example in mind I could work it back and check why it is not shown).

**Comment by trinib** [comment]
tried on amd64 and arm64 same results

https://user-images.githubusercontent.com/18756975/199798475-7276e6b7-07eb-4474-bf89-af0ed17d96c5.mp4

**Comment by trinib** [comment]
it looks like it stops to 100 for all searches

 is use gh s cheat -L 1000

**Comment by gennaro-tedesco** [comment]
I see, I will look into it. I presume it has to do with the maximum number of results returned by GitHub queries, being automatically limited unless specified otherwise.

> like 'user/awesome' = one word and 'user/awesome-python = two, eliminateing all search for one name repos when searching two name repos etc. Maybe search function can find more repos this way?

Could you expand on this? I do not precisely understand. `awesome-python` is treated as one string by the GitHub queries API, which does not possess the concept of words unless we manually split against some delimiters (which we can do but it can open the flood gates to all other sorts of problems when retrieving the results).

Can you find more specific results if you narrow down the search by, say, language or other?

**Comment by trinib** [comment]
for example searching `awesome` will only output all repositories with that one word like `harry/awesome`, `jerry/awesome`, `harry/awesome1`, `jerry/awesome1` <br>
This eliminates searches for the repos with more than one words in its name  like `user/awesome-python` or `user/python-awesome`

a feature to search like one, two,three etc words in the repo name to narrow down search ..

**Comment by trinib** [comment]
> Can you find more specific results if you narrow down the search by, say, language or other?

all the repo can be found with specific parameter but using regular search only shows a limit ..  but can the showing 100 lines only be fixed ?

**Comment by gennaro-tedesco** [comment]
> for example searching awesome will only output all repositories with that one word like

to clarify on this: the search query (you can read more about it [here](https://docs.github.com/en/rest/search#constructing-a-search-query)) returns result that _contain_ any part of the specified string: this is not really in our hands, rather in the search mechanism of the API. 

> This eliminates searches for the repos with more than one words like `user/awesome-python`

again, `awesome-python` is technically still one word string _unless_ we decide to manually split on some delimiters (for instance `-`): in turn this implies that we should define some sort of external logic on what constitutes a word and what not (what characters are you splitting on? There are many projects where `-` is integral part of the title and you should not split it away, likewise for `_/.` and all other punctuation characters). 

>  but can the showing 100 lines at a time be fixed ?

As per the [docs](https://docs.github.com/en/rest/search#search-repositories) 

> This method returns up to 100 results [per page](https://docs.github.com/rest/overview/resources-in-the-rest-api#pagination).

so each pagination returns 100 results at most. Whilst this can of course be worked around by calling each query as many times as to exhaust all the pages, this will increasingly slow down the entire search, because for each single parameter you would have to re-execute the query till exhaustion. I am not excluding this necessarily, however I would like to better understand if the use case justifies making the extension much slower: do you _really_ need to show more than 100 results that cannot be filtered by the additional flags? The flags are there because they have to be used exactly to narrow the search down: so in what use cases you really need more than 100 similar results? :p

**Comment by trinib** [comment]
> again, awesome-python is technically still one word string unless we decide to manually split on some delimiters (for instance -): in turn this implies that we should define some sort of external logic on what constitutes a word and what not (what characters are you splitting on? 

😳😳 yes i did not think this out of the blue question properly .. originally the issue was to find out why is only showing limited repo and i told myself it could be just gh-cli part which you confirmed its could be a api thing and i just wanted to clarify it .

It did not hit me atm about xx-xx-xx being one string and it would be a useless stress on API search function to have it like that and already have extra parameters to find more result.. 

Honesly atm I just taught that it would have solved the missing repos issue in  search without using -t and -d parameters where a user have to think about the `right key words` to find those `no show repos`  with regular search  if you get what im saying 👍
