### ISSUE TITLE
Arrow Keys Are Non-Functional - Win 11.

### ISSUE THREAD

**Issue by klawrawkz** [gennaro-tedesco/gh-s#24]
Howdy. 

This looks cool. There is an issue I experience though. The **_only key that works in Windows Terminal_** is the '/' key. None of the Arrow Keys work, hence the utility is essentially completely useless. See attached mp4s and zip sample.

https://github.com/gennaro-tedesco/gh-s/assets/48074223/60db8428-6403-4c85-8741-b2592fcc23b4

https://github.com/gennaro-tedesco/gh-s/assets/48074223/fadb98a4-c21e-429f-aaca-a92343928fcf

[github-s-utility-broken-arrows.zip](https://github.com/gennaro-tedesco/gh-s/files/12579468/github-s-utility-broken-arrows.zip)

**Comment by gennaro-tedesco** [comment]
I suspect this issue is similar to [this other one](https://github.com/gennaro-tedesco/gh-s/issues/13): essentially the behaviour of the keys in the terminal is responsibility of the `promptui` library that I use; in this respect the extension doesn't set the behaviour of the keys on specific terminals (as such this problem is unfortunately outside the scope of this extension).

In the provided link above other users and I mention long-standing issues that have existed (especially on windows) - thus the best way would be to refer to the owners of `promptui` and have them fix the behaviour on windows terminals :/

**Comment by klawrawkz** [comment]
Gotcha. That's too bad.
