### ISSUE TITLE
Support "Code/Commit/Issues" Search

### ISSUE THREAD

**Issue by jJit0** [gennaro-tedesco/gh-s#8]
Hi,

I love your tool, very modern and intuitive, but it misses few things, like searching for code, commits, issues, users, etc...

I'm currently using this one for searching code, very similar to your tool, but nodejs: https://github.com/feinoujc/gh-search-cli

**Comment by gennaro-tedesco** [comment]
Hi, good morning and thank your for your suggestion! Let me provide some context: this extension calls the GitHub endpoint `search/repositories/` as described [here](https://docs.github.com/en/rest/reference/search#search-repositories), which means that anything (or rather, any argument) indicated in the [details here](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories) can in principle be added for search.

However, search for commits/issues/users call different endpoints (see [/search/commits](https://docs.github.com/en/rest/reference/search#search-commits) and links therein), implying in turn that the grammar, the arguments and the parsing follow other logic. Whilst it _can_ technically be done (one could add a sub-command for a different endpoint) I would say this falls outside the scope of this extension (imagine users having to remember that maybe this flag works with `/commits`, this other flag works only with `/issues/` and so forth).

However, since this project is gaining good traction, one idea could be to just implement another extension which more or less works as copy and paste of this one (same logic, same ui) only calling a different endpoint (which will be whatever you like of `/issues/code/users` and so on). What do you think? I am open to suggestions :)

**Comment by jJit0** [comment]
I agree, very good idea.

Adding another sub-command, or extension, can be useful to swich between searching repos, codes, commits or issues.

If you implement this feature anytime soon, do I need to use my github_personal_token to search codes or issues ?

**Comment by gennaro-tedesco** [comment]
@jJit0 I have prepared a draft of what we discussed in a new extension [gh-i](https://github.com/gennaro-tedesco/gh-i): it searches for issues providing a range of flags to narrow down the search by title, body, label and so forth. It is obviously unpolished and quick, would you like to test it locally to see if this is along the lines of what you intended? Since there is no release yet you would have to clone the repository and `gh extension install .`.

**Comment by gennaro-tedesco** [comment]
The [first release](https://github.com/gennaro-tedesco/gh-i/releases/tag/v0.0.1) of [gh-i](https://github.com/gennaro-tedesco/gh-i) is out. This should (at least partially) address the topic at hand here :)
